db.UserTable.ensureIndex({field0 : 1});
db.UserTable.ensureIndex({field1 : 1});
db.UserTable.ensureIndex({field2 : 1});
db.UserTable.ensureIndex({field3 : 1});
db.UserTable.ensureIndex({field4 : 1});
db.UserTable.ensureIndex({field5 : 1});
db.UserTable.ensureIndex({field6 : 1});
db.UserTable.ensureIndex({field7 : 1});
db.UserTable.ensureIndex({field8 : 1});
