---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: couchbase-backup
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - get
  - list
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - couchbase.com
  resources:
  - couchbasebackups
  - couchbasebackuprestores
  verbs:
  - get
  - list
  - watch
  - patch
  - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: couchbase-backup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: couchbase-backup
subjects:
- kind: ServiceAccount
  name: couchbase-backup
  namespace: default

---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: couchbase-backup