apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    config.couchbase.com/version: 2.2.0
  creationTimestamp: null
  name: couchbase-operator-admission
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    config.couchbase.com/version: 2.2.0
  creationTimestamp: null
  name: couchbase-operator-admission
rules:
- apiGroups:
  - couchbase.com
  resources:
  - couchbaseclusters
  - couchbasebuckets
  - couchbaseephemeralbuckets
  - couchbasememcachedbuckets
  - couchbasereplications
  - couchbaseusers
  - couchbasegroups
  - couchbaserolebindings
  - couchbasebackups
  - couchbasebackuprestores
  - couchbaseautoscalers
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    config.couchbase.com/version: 2.2.0
  creationTimestamp: null
  name: couchbase-operator-admission
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: couchbase-operator-admission
subjects:
- kind: ServiceAccount
  name: couchbase-operator-admission
  namespace: default
---
apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURoekNDQW0rZ0F3SUJBZ0lRSkViRndvY2dDN0d2cnBIMVZCWlVnREFOQmdrcWhraUc5dzBCQVFzRkFEQXEKTVNnd0pnWURWUVFERXg5amIzVmphR0poYzJVdGIzQmxjbUYwYjNJdFlXUnRhWE56YVc5dUlFTkJNQjRYRFRJeApNRFF5TVRFMk5EWXpNVm9YRFRNeE1EUXhPVEUyTkRZek1Wb3dKekVsTUNNR0ExVUVBeE1jWTI5MVkyaGlZWE5sCkxXOXdaWEpoZEc5eUxXRmtiV2x6YzJsdmJqQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0MKZ2dFQkFMZHNuemNsc0wwRlFzQ052aDJibk9RZklsMUFaUVVZaERSUXIwbzBZcVRjUTlhLzYvZTNyclBsbnpTZgp5ZGRVUmlTQ3M2YlBWWEttZVgyeXBjNGtORHBNODhORWdDV0owWHMraVlNb2ZoalNnVlZhajRiQnJGWUZOWW9xCmpaWlI2c1l4TGtzNXI3eUEzR1NzQ1RjbzlxMXpPVmovRW90OEZHK3Jua1hWb29wNmlDVXRDNkpnUjNtN09Jd2UKcFlLcWhFcWFSaWFVajc5Q1NTVWN3cnpWWDBoNlprUUZUTjZ0VU1oZ0Q0S2JpMXlUVGFlSmVtdkNZMkJxb3FRRwpydkJid1dUTi9sdVBNdDNEOGVDRE9KN2RXS1VUYkMvRXppcnk4WitQZUVvc1ZtQ1NTNkNRckhoN1hqaitKbkFPCmZKQTN0c21odk9IeGVOVDlTMUoyVHRHbmJEa0NBd0VBQWFPQnF6Q0JxREFPQmdOVkhROEJBZjhFQkFNQ0JhQXcKRXdZRFZSMGxCQXd3Q2dZSUt3WUJCUVVIQXdFd0RBWURWUjBUQVFIL0JBSXdBREFkQmdOVkhRNEVGZ1FVQzZ4Tgp1elkvcWZWN0NPUjhlWkF4dldOcVp5MHdId1lEVlIwakJCZ3dGb0FVbk9IMWhlb0s1aGcyVTUrdTdrYlI1bG9wCmU2a3dNd1lEVlIwUkJDd3dLb0lvWTI5MVkyaGlZWE5sTFc5d1pYSmhkRzl5TFdGa2JXbHpjMmx2Ymk1a1pXWmgKZFd4MExuTjJZekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBNllmaFR4N1BWT0hPK2VvYzRZZ0lPakpnUnE0Sgo3TnBXd05IaUVIK1JxTzRhUWhraGoyYldwYSt1Y0RVaTE3aWJjd2Q2L0FpZ0oxNnZ0MU9icjU5aXlrUDFpZkF4ClZCMG96RTh2RjV4RUtFZVRBYTltMFFpMXlnL0h1SmVMWlZFZGg2anE0WndOcnZJR3lNVnNPNTlLUmViNHVHY2EKL01LbHFNcGduenZlMWVuTkdHajlubXRBT1ZaazNkTWY5M1BkUUIreTFIL0d4RXVUZ3p5UDYvNlVZL3o5eDhXTgp1TTlSa0E5QmpkQ1F5Tms0dmhOMERXcGlJMG5IT3JFRWdORHQ1RzFaL1lPUUJkUHppYk9XanZqYU4zWmRMUktvCkRqZDlIbGdBbzltQmRPdWlleXBjak52c2tWelh3K2UzU0NTTVZSNzN4Qk1NQnlsd09ycXBUTmdaeEE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBdDJ5Zk55V3d2UVZDd0kyK0hadWM1QjhpWFVCbEJSaUVORkN2U2pSaXBOeEQxci9yCjk3ZXVzK1dmTkovSjExUkdKSUt6cHM5VmNxWjVmYktsemlRME9renp3MFNBSlluUmV6NkpneWgrR05LQlZWcVAKaHNHc1ZnVTFpaXFObGxIcXhqRXVTem12dklEY1pLd0pOeWoyclhNNVdQOFNpM3dVYjZ1ZVJkV2lpbnFJSlMwTApvbUJIZWJzNGpCNmxncXFFU3BwR0pwU1B2MEpKSlJ6Q3ZOVmZTSHBtUkFWTTNxMVF5R0FQZ3B1TFhKTk5wNGw2CmE4SmpZR3FpcEFhdThGdkJaTTMrVzQ4eTNjUHg0SU00bnQxWXBSTnNMOFRPS3ZMeG40OTRTaXhXWUpKTG9KQ3MKZUh0ZU9QNG1jQTU4a0RlMnlhRzg0ZkY0MVAxTFVuWk8wYWRzT1FJREFRQUJBb0lCQUN2a0FBMHdKYVIxVjgyLwpuUmgwbmd3d0x3YmxXOGJtWU93cnltWVZOdTJBRDNPWnBSczNoc1JoVThGQjR3aDFqL3M0azBoOUlGTTQ1cVZmClZER0psRDNISUNVL2hQSjJrZnZOc1JZRFlIa01GZ3FZaXZPUjhHejgvaHk3cGZtc1RHTjBiVUZ1NGxCVy9XWFIKakxyNFFGNnN6Ykl3QnYzOWlONVgwSjJoU3kyYlQvZHVEZFNXS04vdy96Uzh6R3lTK0RZdm1EYnV3MjcyZHg5SgpaQlE1Mkt0cFJDeUdhMkpjN1czOHR4bElLY0FTT0lVVnpLMEVnVE5QajZhUitDWnZlSlhUTVF2emNIY2FHRlcyCmhacStDNmhyb3lNYnpTbWxFNDlYVEJVT0V2aVJVZWFaeDhRU3llWmxqVXdIemEyWUFlREE1UFBvcTRBRy93V2wKbk1xZ1F5RUNnWUVBOUd6YmhlNGVDVGU1R2hTN2pUQ3VRcTJQbDNGRmN0YzA4cm4yK2prRTNRK1BiYnhza2xrTwp4VTd4cE5qSlpRYklkc0ZHYXpzdmIwRUd4aVZIbHEzejJNMDU0RThwa1JyMGZCaXRlV0lEbDdSUGxGOVBzRVhOCjRQOWVnQVR3TDdwWC9aMW9jU2w4NitSSzE2RnBDYjVROFNJL3c2VDNDcGZzOUl6TnFmeWV5N1VDZ1lFQXdCeEIKb21SZCtJMEJRRnc1SDBqaTRCS0QvOHlyY0NJSnh3ZFUzNUkvRzhnL1gvOVgwdmFVVkVBSVBaTkZ4bmxoVHY1UgpxRVJmWmI1cEVjYWxRZnBqZS9zUU8vZ0VJcTdCTy83RTRQR0FybEt3eUlXOTBrb1BBZHlUNThicDhNMENpR1BOCmw2UmNtMERUZ1REM2YveTk3OXMveTRSQnh6SUZPS0J0dlBTdm1QVUNnWUJvNk1ROE10emZkZlJUMW13OWlKUnkKK0EyMm9aNStVUkpmMENQS2VHaTIvVFBCbE90QTBVcStzMGlTU1ozL1o2N3BFY0hJeXFsc1pndWpSbUw0c0ljRwpHZWZxZCsvT1lUUm9neXNKKzJDeFgybjhzLy8vRjZickdKQ1dBQWliWTY3YW94SXQ1L0cvU2NnNXp3VEhjdEZJCi9qdENITzhQcysrM2N5dmU5eGV0TlFLQmdIdm12WDRhOVhDRW9MWDl4T21rZkk2LzRscHNpblY3dm9xYTgrWnQKMEQzKzNNRHhVcGRCYVZFZEt6TnJkS2taUitWR3FTdTVUVDIxbk5aV0krZDFzZ3dZVk5RWWxiSTR1M0FTVkxBdgpraXJjTWlCaUFaZExKSHF5NU1HcnpOMzlteENVTGRrTHJKNkZKT1JCeko3RFIwMFhQd0huZnZVV0ViLy8yRWJ5CkdQNnhBb0dBYjZXUklXdXdnSHc4WExOZmtRbG9DV2FycmszNTZBWWgxY0l6aGZZcWhWV2Fmb1ZnWXNwZGI4QUkKK3lvMmFlaS91dllid2oydjN5TmRwb0NSYUE1eUxYQmhYR3JJS1UrYjM4N0RISldMcjJCbWw0OXpJd0ZOYkVragpxYXVCczR5S3hZNXNZbU9NZGtucXNQdjhXRUFWMVUxTDB3TjFrS09wUXB0cW42c2lkeEE9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
kind: Secret
metadata:
  annotations:
    config.couchbase.com/version: 2.2.0
  creationTimestamp: null
  name: couchbase-operator-admission
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    config.couchbase.com/version: 2.2.0
  creationTimestamp: null
  name: couchbase-operator-admission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchbase-operator-admission
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: couchbase-operator-admission
    spec:
      containers:
      - args:
        - -zap-log-level=info
        - -tls-cert-file=/var/run/secrets/couchbase.com/couchbase-operator-admission/tls.crt
        - -tls-private-key-file=/var/run/secrets/couchbase.com/couchbase-operator-admission/tls.key
        - -validate-secrets=true
        - -validate-storage-classes=true
        - -default-file-system-group=true
        command:
        - couchbase-operator-admission
        image: couchbase/admission-controller:build
        name: couchbase-operator-admission
        ports:
        - containerPort: 8443
          name: https
        readinessProbe:
          httpGet:
            path: /readyz
            port: https
            scheme: HTTPS
        resources: {}
        volumeMounts:
        - mountPath: /var/run/secrets/couchbase.com/couchbase-operator-admission
          name: couchbase-operator-admission
          readOnly: true
      imagePullSecrets:
      - name: regcred
      serviceAccountName: couchbase-operator-admission
      volumes:
      - name: couchbase-operator-admission
        secret:
          secretName: couchbase-operator-admission
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    config.couchbase.com/version: 2.2.0
  creationTimestamp: null
  name: couchbase-operator-admission
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: couchbase-operator-admission
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    config.couchbase.com/version: 2.2.0
  creationTimestamp: null
  name: couchbase-operator-admission
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJVENDQWdtZ0F3SUJBZ0lSQVBZZjNHaXQzSWdXbmlOelpFSm0zakF3RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZlkyOTFZMmhpWVhObExXOXdaWEpoZEc5eUxXRmtiV2x6YzJsdmJpQkRRVEFlRncweQpNVEEwTWpFeE5qUTJNekZhRncwek1UQTBNVGt4TmpRMk16RmFNQ294S0RBbUJnTlZCQU1USDJOdmRXTm9ZbUZ6ClpTMXZjR1Z5WVhSdmNpMWhaRzFwYzNOcGIyNGdRMEV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUUR4Z3IwU0ZmTlVpT3dubkFtNmdYUDhqR0pNdEJwOVFlY1k4ekU0amxlUlFtbTlKUStjRDc3RQpDeUs2YTF3cGZuWDJFWklzWkNBaDViTGxPWjJ5Y1BtUkE3MHNaOHc2eWdOZGpaZ2hiaDcwRk5wRXd5MXJxQXhLCjM1UkROdURQVE4xbVhJNElDTHpReXREdFlJZGVKbEN5UHFWdVJ3OE1OUms2Z1JaQm0xaWFnTW95VzI5UUFnc2kKOENVUFlqWW5FSmNUaGk1UmVKQVNUVE5LbWkzdEZyMHVOeWdoZHZpSCsvOVp5azE2aWNVMVM5TUQ3Sm5UQkovZwpjN2FCZHVnTWhualc5VllncGVyaEdOTFkzNkJ4TEpRS2NEWFpqc2Q0ZFc2MUErWGRwemRKN0s0YjFxWFJUUG1LCmdRK2ZWNzRsVnlkMXFpeWNQZG5MQytJOUpHWmlxR3Y5QWdNQkFBR2pRakJBTUE0R0ExVWREd0VCL3dRRUF3SUIKQmpBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTYzRmV0Y2Z3JtR0RaVG42N3VSdEhtV2lsNwpxVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBM3k4L3BhTXUzZTRGSFhVWVBnUWxUQW5JOWFVZUxJdEtxUk5YClIrRnNHOUtqRXF5Q2pIcExlbGlSVGVOc0ZqRWhwMWMvWnVvdzIvemJWb1cybFc2RUNhV0J6SkQ1dmg5dTMzR04KOEJsOWNxa2RFSENXQ0puYW9RNjVBWjMzamYxL3piMGptVXRyUUx1RWJ4VVl1c09LU1ZsSmp1cUVaY1dVaFUzKwpwcC9ManI5SGVjci9Tc3Z6ZlZRcGFVOWtUWDN1bjVBRC9FZElqbStQZzRKdU5DMGc4bWh0MkQ0ZUpleVFUN1pTCkN4TFRzb3VrMUsxQnBLQktnb2k0QzFoaW5kMTFCcDgybXRkbzhHVlVSOWZuUG5iaTcyaWQvMFZZaWdvcDF3VnMKbkU4Q2M3alV6cWZaUnZ5WFV6R282dUFYbmJxSWMxeTd0K3ozSkgyV0FURTZQRkd6UHc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: couchbase-operator-admission
      namespace: default
      path: /couchbaseclusters/validate
  failurePolicy: Fail
  name: couchbase-operator-admission.default.svc
  rules:
  - apiGroups:
    - couchbase.com
    apiVersions:
    - v1
    - v2
    operations:
    - CREATE
    - UPDATE
    resources:
    - couchbaseclusters
    - couchbasebuckets
    - couchbaseephemeralbuckets
    - couchbasememcachedbuckets
    - couchbasereplications
    - couchbaseusers
    - couchbasegroups
    - couchbaserolebindings
    - couchbasebackups
    - couchbasebackuprestores
    - couchbaseautoscalers
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    config.couchbase.com/version: 2.2.0
  creationTimestamp: null
  name: couchbase-operator-admission
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJVENDQWdtZ0F3SUJBZ0lSQVBZZjNHaXQzSWdXbmlOelpFSm0zakF3RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZlkyOTFZMmhpWVhObExXOXdaWEpoZEc5eUxXRmtiV2x6YzJsdmJpQkRRVEFlRncweQpNVEEwTWpFeE5qUTJNekZhRncwek1UQTBNVGt4TmpRMk16RmFNQ294S0RBbUJnTlZCQU1USDJOdmRXTm9ZbUZ6ClpTMXZjR1Z5WVhSdmNpMWhaRzFwYzNOcGIyNGdRMEV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUUR4Z3IwU0ZmTlVpT3dubkFtNmdYUDhqR0pNdEJwOVFlY1k4ekU0amxlUlFtbTlKUStjRDc3RQpDeUs2YTF3cGZuWDJFWklzWkNBaDViTGxPWjJ5Y1BtUkE3MHNaOHc2eWdOZGpaZ2hiaDcwRk5wRXd5MXJxQXhLCjM1UkROdURQVE4xbVhJNElDTHpReXREdFlJZGVKbEN5UHFWdVJ3OE1OUms2Z1JaQm0xaWFnTW95VzI5UUFnc2kKOENVUFlqWW5FSmNUaGk1UmVKQVNUVE5LbWkzdEZyMHVOeWdoZHZpSCsvOVp5azE2aWNVMVM5TUQ3Sm5UQkovZwpjN2FCZHVnTWhualc5VllncGVyaEdOTFkzNkJ4TEpRS2NEWFpqc2Q0ZFc2MUErWGRwemRKN0s0YjFxWFJUUG1LCmdRK2ZWNzRsVnlkMXFpeWNQZG5MQytJOUpHWmlxR3Y5QWdNQkFBR2pRakJBTUE0R0ExVWREd0VCL3dRRUF3SUIKQmpBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTYzRmV0Y2Z3JtR0RaVG42N3VSdEhtV2lsNwpxVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBM3k4L3BhTXUzZTRGSFhVWVBnUWxUQW5JOWFVZUxJdEtxUk5YClIrRnNHOUtqRXF5Q2pIcExlbGlSVGVOc0ZqRWhwMWMvWnVvdzIvemJWb1cybFc2RUNhV0J6SkQ1dmg5dTMzR04KOEJsOWNxa2RFSENXQ0puYW9RNjVBWjMzamYxL3piMGptVXRyUUx1RWJ4VVl1c09LU1ZsSmp1cUVaY1dVaFUzKwpwcC9ManI5SGVjci9Tc3Z6ZlZRcGFVOWtUWDN1bjVBRC9FZElqbStQZzRKdU5DMGc4bWh0MkQ0ZUpleVFUN1pTCkN4TFRzb3VrMUsxQnBLQktnb2k0QzFoaW5kMTFCcDgybXRkbzhHVlVSOWZuUG5iaTcyaWQvMFZZaWdvcDF3VnMKbkU4Q2M3alV6cWZaUnZ5WFV6R282dUFYbmJxSWMxeTd0K3ozSkgyV0FURTZQRkd6UHc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: couchbase-operator-admission
      namespace: default
      path: /couchbaseclusters/mutate
  failurePolicy: Fail
  name: couchbase-operator-admission.default.svc
  rules:
  - apiGroups:
    - couchbase.com
    apiVersions:
    - v1
    - v2
    operations:
    - CREATE
    - UPDATE
    resources:
    - couchbaseclusters
    - couchbasebuckets
    - couchbaseephemeralbuckets
    - couchbasememcachedbuckets
    - couchbasereplications
    - couchbaseusers
    - couchbasegroups
    - couchbaserolebindings
    - couchbasebackups
    - couchbasebackuprestores
    - couchbaseautoscalers
  sideEffects: None
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    config.couchbase.com/version: 2.2.0
  creationTimestamp: null
  name: couchbase-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    config.couchbase.com/version: 2.2.0
  creationTimestamp: null
  name: couchbase-operator
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - couchbase.com
  resources:
  - couchbaseclusters
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - couchbase.com
  resources:
  - couchbasebuckets
  - couchbaseephemeralbuckets
  - couchbasememcachedbuckets
  - couchbasereplications
  - couchbaseusers
  - couchbasegroups
  - couchbaserolebindings
  - couchbasebackups
  verbs:
  - list
  - watch
- apiGroups:
  - couchbase.com
  resources:
  - couchbasebackuprestores
  verbs:
  - list
  - watch
  - delete
- apiGroups:
  - couchbase.com
  resources:
  - couchbaseautoscalers
  verbs:
  - list
  - watch
  - create
  - delete
- apiGroups:
  - couchbase.com
  resources:
  - couchbaseautoscalers/status
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - create
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  - pods/status
  - services
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - list
  - create
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - create
  - update
  - list
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - get
  - create
  - delete
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    config.couchbase.com/version: 2.2.0
  creationTimestamp: null
  name: couchbase-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: couchbase-operator
subjects:
- kind: ServiceAccount
  name: couchbase-operator
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    config.couchbase.com/version: 2.2.0
  creationTimestamp: null
  name: couchbase-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchbase-operator
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: couchbase-operator
    spec:
      containers:
      - args:
        - --pod-create-timeout=10m0s
        - --zap-log-level=info
        command:
        - couchbase-operator
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: couchbase/operator:build
        name: couchbase-operator
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8383
          name: prometheus
        readinessProbe:
          httpGet:
            path: /readyz
            port: http
            scheme: HTTP
        resources: {}
      imagePullSecrets:
      - name: regcred
      serviceAccountName: couchbase-operator
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    config.couchbase.com/version: 2.2.0
  creationTimestamp: null
  name: couchbase-operator
spec:
  ports:
  - name: http-pprof
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: http-prometheus
    port: 8383
    protocol: TCP
    targetPort: 8383
  selector:
    app: couchbase-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    config.couchbase.com/version: 2.2.0
  creationTimestamp: null
  name: couchbase-backup
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    config.couchbase.com/version: 2.2.0
  creationTimestamp: null
  name: couchbase-backup
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - couchbase.com
  resources:
  - couchbasebackups
  - couchbasebackuprestores
  verbs:
  - get
  - list
  - watch
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    config.couchbase.com/version: 2.2.0
  creationTimestamp: null
  name: couchbase-backup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: couchbase-backup
subjects:
- kind: ServiceAccount
  name: couchbase-backup
  namespace: default