# Stop sync_gateway service
- name: SYNC GATEWAY | Stop sync_gateway service
  service:
    name: sync_gateway
    state: stopped
  when: ansible_facts['os_family'] == "Debian" and ansible_facts['distribution_major_version'] | int >= 20
  ignore_errors: yes

# Remove sync_gateway package
- name: SYNC GATEWAY | Uninstall sync_gateway
  apt:
    name: couchbase-sync-gateway
    state: absent
  ignore_errors: yes

# Remove sync_gateway service
- name: SYNC GATEWAY | Remove sync_gateway service
  file: path=/usr/lib/systemd/system/sync_gateway.service state=absent
  ignore_errors: yes

# Delete sync_gateway binary
- name: SYNC GATEWAY | Delete sync_gateway binary
  file: path=/opt/couchbase-sync-gateway state=absent
  ignore_errors: yes

- name: SYNC GATEWAY | Remove tmp logging dir (log rotation tests)
  shell: rm -rf /tmp/sg_logs
  ignore_errors: yes

- name: SYNC GATEWAY | Remove var/tmp/sglogs dir
  shell: rm -rf /var/tmp/sglogs/*
  ignore_errors: yes
