"""X.509 material for TLS between perfrunner, the workload workers and the cluster.

`SSLCertificate` issues everything a run needs from one self-signed CA: the node certificate
the cluster presents, the client certificate `ssl_mode = auth` workloads authenticate with,
and a CRL for tests that exercise revocation. `summarise_keystore` reads back the Java
keystore those certificates are imported into.

Split out of `perfrunner.helpers.misc`, which it does not depend on.
"""

import datetime
import ipaddress
import os
from typing import NamedTuple, Optional

from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric.rsa import RSAPrivateKey, generate_private_key
from cryptography.hazmat.primitives.serialization import pkcs12
from cryptography.x509 import (
    AuthorityKeyIdentifier,
    BasicConstraints,
    Certificate,
    CertificateBuilder,
    CertificateRevocationList,
    CertificateRevocationListBuilder,
    CertificateSigningRequest,
    CertificateSigningRequestBuilder,
    CRLNumber,
    DNSName,
    ExtendedKeyUsage,
    ExtendedKeyUsageOID,
    ExtensionNotFound,
    GeneralName,
    IPAddress,
    KeyUsage,
    Name,
    NameAttribute,
    RevokedCertificateBuilder,
    SubjectAlternativeName,
    SubjectKeyIdentifier,
    load_pem_x509_certificate,
    load_pem_x509_crl,
    random_serial_number,
)
from cryptography.x509.oid import NameOID

from logger import logger

KEYSTORE_SUMMARY_FIELDS = ('Alias name', 'Entry type', 'Owner', 'Issuer')


def summarise_keystore(listing: str) -> str:
    """Reduce `keytool -list -v` output to the entry and issuer lines worth logging."""
    return "\n".join(
        line.rstrip() for line in listing.splitlines()
        if line.startswith(KEYSTORE_SUMMARY_FIELDS)
    )


class X509CertPathPair(NamedTuple):
    cert_path: str
    key_path: str


class SSLCertificate:

    """Generate X.509 certificates for either cluster nodes or clients.

    Calling `generate_server_cert()` will create a node certificate with SAN including all node IPs.

    Calling `generate_client_cert()` will create a client cert with CN set to the desired username
    for authenticating with the cluster, stored both as a PEM pair and as a PKCS#12 bundle: the
    Python SDK and `requests` take the PEM pair, `keytool` can only import the bundle.

    Calling `generate_crl()` will create a (by default empty) CRL for the CA, for tests that
    exercise revocation checking.

    A self-signed root certificate is generated to sign node/client certificates. If a CA is
    already present in the output directory it is reused, so node and client certificates
    generated by separate calls share the same trust chain.

    Everything is written to `INBOX` unless the caller passes `output_dir`. Only the standalone
    `x509_cert` CLI does: the perfrunner flow reads the artefacts back through the `*_PATH`
    constants, which name the inbox and nothing else.
    """

    INBOX_DIRNAME = "inbox"
    INBOX = f"certificates/{INBOX_DIRNAME}"

    # The CN has to name an existing Couchbase RBAC user: `enable_certificate_auth` maps the whole
    # CN to the username. `add_rbac_users` runs before certificate setup and creates the cluster
    # spec's REST user with the admin role, so that name is the one identity every test has,
    # buckets or not. Callers with a spec to hand should pass its REST user rather than rely on
    # this default matching.
    DEFAULT_CLIENT_CN = "Administrator"
    DEFAULT_STOREPASS = "storepass"

    # The PKCS#12 friendlyName, which is the alias `keytool` addresses the entry by.
    CLIENT_BUNDLE_ALIAS = "client"

    CERT_VALIDITY = datetime.timedelta(days=60)
    MIN_CA_VALIDITY = datetime.timedelta(days=7)

    # File names are useful on their own: certificates are staged under bare names elsewhere
    # (on cluster nodes and on workload workers), where the inbox path does not apply.
    CA_CERT_FILENAME = "ca.pem"
    CA_KEY_FILENAME = "ca.key"
    CRL_FILENAME = "ca.crl"

    SERVER_CERT_FILENAME = "chain.pem"
    SERVER_KEY_FILENAME = "pkey.key"

    CLIENT_CERT_FILENAME = "client.pem"
    CLIENT_KEY_FILENAME = "client.key"
    CLIENT_BUNDLE_FILENAME = "client.p12"

    # Where readers outside this class find each artefact. Writing goes through `path()`
    # instead, so `output_dir` can point elsewhere; these stay pinned to the inbox.
    CA_CERT_PATH = f"{INBOX}/{CA_CERT_FILENAME}"
    CA_KEY_PATH = f"{INBOX}/{CA_KEY_FILENAME}"
    CRL_PATH = f"{INBOX}/{CRL_FILENAME}"

    SERVER_CERT_PATH = f"{INBOX}/{SERVER_CERT_FILENAME}"
    SERVER_KEY_PATH = f"{INBOX}/{SERVER_KEY_FILENAME}"

    CLIENT_CERT_PATH = f"{INBOX}/{CLIENT_CERT_FILENAME}"
    CLIENT_KEY_PATH = f"{INBOX}/{CLIENT_KEY_FILENAME}"
    CLIENT_BUNDLE_PATH = f"{INBOX}/{CLIENT_BUNDLE_FILENAME}"

    def __init__(self, hosts: Optional[list[str]] = None, output_dir: str = INBOX):
        self.hosts = hosts or ["127.0.0.1"]
        self.output_dir = output_dir
        self.not_valid_before = datetime.datetime.now(datetime.timezone.utc)
        self.not_valid_after = self.not_valid_before + self.CERT_VALIDITY

    def path(self, filename: str) -> str:
        """Where this instance writes `filename`, and where it looks for a CA to reuse."""
        return os.path.join(self.output_dir, filename)

    @staticmethod
    def _describe(cert: Certificate) -> str:
        """Identify a certificate in the log.

        A handshake failure names the issuer and validity it objected to and nothing else, so
        these are what let a run's certificates be matched against what the cluster presents.
        """
        return (
            f"subject={cert.subject.rfc4514_string()}, "
            f"issuer={cert.issuer.rfc4514_string()}, "
            f"serial={cert.serial_number:x}, "
            f"valid {cert.not_valid_before_utc:%Y-%m-%d} to {cert.not_valid_after_utc:%Y-%m-%d}"
        )

    def generate_server_cert(self):
        """
        Generate signed node certificate and store it and its key to the output directory.

        If CA certificate and private key aren't already there, generate them too.
        """
        logger.info(f"Generating certificates in {os.path.abspath(self.output_dir)} "
                    f"with SANs: {sorted(self.hosts)}")
        # Generate CA first
        ca_key, ca = self.maybe_generate_ca()

        # Certificate signing request. Both serverAuth and clientAuth: under node-to-node
        # encryption a node is also a TLS client of other nodes (the master connecting to a node
        # being added during rebalance, for instance), which serverAuth alone does not permit.
        request_key, req = self.generate_signing_request(
            ca,
            "Couchbase Server",
            [ExtendedKeyUsageOID.SERVER_AUTH, ExtendedKeyUsageOID.CLIENT_AUTH],
        )

        # Node certificate
        cert = CertificateBuilder(
            issuer_name=ca.subject,
            subject_name=req.subject,
            public_key=req.public_key(),
            serial_number=random_serial_number(),
            not_valid_before=self.not_valid_before,
            not_valid_after=self.not_valid_after,
            extensions=req.extensions
        ).sign(ca_key, hashes.SHA256())

        # Store key/chain using appropriate names
        self._store_key(self.path(self.SERVER_KEY_FILENAME), request_key)
        self._store_cert(self.path(self.SERVER_CERT_FILENAME), cert)
        logger.info(f"Generated node certificate: {self._describe(cert)}")

    def generate_client_cert(
        self, username: str = DEFAULT_CLIENT_CN, storepass: str = DEFAULT_STOREPASS
    ) -> X509CertPathPair:
        """
        Generate signed client certificate and store it and its key to the output directory.

        The certificate and key are stored as a PEM pair and as a PKCS#12 bundle encrypted with
        `storepass`. The PEM pair is what the Python SDK and `requests` take; `keytool` can only
        import the bundle, so both are written from the same key pair.

        If CA certificate and private key aren't already there, generate them too.
        """
        ca_key, ca = self.maybe_generate_ca()

        # Certificate signing request
        client_key, client_csr = self.generate_signing_request(
            ca, username, [ExtendedKeyUsageOID.CLIENT_AUTH]
        )

        # Sign the client certificate
        client_cert = CertificateBuilder(
            issuer_name=ca.subject,
            subject_name=client_csr.subject,
            public_key=client_csr.public_key(),
            serial_number=random_serial_number(),
            not_valid_before=self.not_valid_before,
            not_valid_after=self.not_valid_after,
            extensions=client_csr.extensions,
        ).sign(ca_key, hashes.SHA256())

        # Store individual files
        key_filepath = self._store_key(self.path(self.CLIENT_KEY_FILENAME), client_key)
        cert_filepath = self._store_cert(self.path(self.CLIENT_CERT_FILENAME), client_cert)
        self._store_pkcs12(client_key, client_cert, ca, storepass)
        logger.info(f"Generated client certificate: {self._describe(client_cert)}")

        return X509CertPathPair(cert_filepath, key_filepath)

    def generate_crl(self, revoked_serial_numbers: Optional[list[int]] = None) -> str:
        """
        Generate a CRL for the CA and store it, revoking the given serial numbers.

        The CRL is empty unless serial numbers are passed, so that tests enforcing revocation
        checking have something to upload from the start. Returns the path it was stored at.

        If CA certificate and private key aren't already there, generate them too.
        """
        ca_key, ca = self.maybe_generate_ca()

        builder = (
            CertificateRevocationListBuilder()
            .issuer_name(ca.subject)
            .last_update(self.not_valid_before)
            # Deliberately the certificate lifetime rather than something shorter: past
            # nextUpdate a validator may treat the CRL as stale and, under a policy that
            # requires CRLs, fail closed part-way through a long-running test.
            .next_update(self.not_valid_after)
            .add_extension(CRLNumber(self._next_crl_number()), critical=False)
        )

        for serial_number in revoked_serial_numbers or []:
            builder = builder.add_revoked_certificate(
                RevokedCertificateBuilder()
                .serial_number(serial_number)
                .revocation_date(self.not_valid_before)
                .build()
            )

        return self._store_crl(self.path(self.CRL_FILENAME), builder.sign(ca_key, hashes.SHA256()))

    def generate_ca(self) -> tuple[RSAPrivateKey, Certificate]:
        """Generate a certificate that can be used as a Certificate Authority (CA)."""
        ca_key_pair = self._make_key_pair()
        subject = self._get_subject('Couchbase Root CA')
        ca = (
            CertificateBuilder(
                issuer_name=subject,
                subject_name=subject,
                public_key=ca_key_pair.public_key(),
                serial_number=random_serial_number(),
                not_valid_before=self.not_valid_before,
                not_valid_after=self.not_valid_after,
            )
            .add_extension(BasicConstraints(ca=True, path_length=None), critical=True)
            .add_extension(
                SubjectKeyIdentifier.from_public_key(ca_key_pair.public_key()), critical=False
            )
            .add_extension(
                # crl_sign: this CA signs the CRL in `generate_crl()`, so its KeyUsage has to assert
                # cRLSign (RFC 5280 4.2.1.3) for validators to accept it as the CRL issuer.
                KeyUsage(
                    digital_signature=True,
                    content_commitment=False,
                    key_encipherment=True,
                    data_encipherment=False,
                    key_agreement=False,
                    key_cert_sign=True,
                    crl_sign=True,
                    encipher_only=False,
                    decipher_only=False,
                ),
                critical=True,
            )
            .sign(ca_key_pair, hashes.SHA256())
        )

        # Store CA
        self._store_cert(self.path(self.CA_CERT_FILENAME), ca)
        self._store_key(self.path(self.CA_KEY_FILENAME), ca_key_pair)
        logger.info(f"Generated CA: {self._describe(ca)}")
        return ca_key_pair, ca

    def generate_signing_request(
        self, ca: Certificate, common_name: str, eku_oids: list[ExtendedKeyUsageOID]
    ) -> tuple[RSAPrivateKey, CertificateSigningRequest]:
        """Generate a CSR and a private key that can be used to generate a certificate."""
        pkey = self._make_key_pair()
        server_auth = ExtendedKeyUsageOID.SERVER_AUTH in eku_oids

        req = (
            CertificateSigningRequestBuilder()
            .subject_name(self._get_subject(common_name))
            .add_extension(BasicConstraints(ca=False, path_length=None), critical=True)
            .add_extension(SubjectKeyIdentifier.from_public_key(pkey.public_key()), critical=False)
            .add_extension(
                AuthorityKeyIdentifier.from_issuer_public_key(ca.public_key()), critical=False
            )
            .add_extension(
                KeyUsage(
                    digital_signature=True,
                    content_commitment=False,
                    key_encipherment=server_auth,
                    data_encipherment=False,
                    key_agreement=False,
                    key_cert_sign=False,
                    crl_sign=False,
                    encipher_only=False,
                    decipher_only=False,
                ),
                critical=True,
            )
            .add_extension(ExtendedKeyUsage(eku_oids), critical=False)
        )

        if server_auth:
            san_list = [self._get_general_name(host) for host in self.hosts]
            req = req.add_extension(SubjectAlternativeName(san_list), critical=False)

        req = req.sign(pkey, hashes.SHA256())

        return pkey, req

    def maybe_generate_ca(self) -> tuple[RSAPrivateKey, Certificate]:
        if self._check_if_ca_exists():
            ca_key, ca = self.load_ca()
            if self._ca_is_usable(ca):
                self.not_valid_after = min(self.not_valid_after, ca.not_valid_after_utc)
                return ca_key, ca
            # Jenkins checks the repo out from scratch for every run, so the inbox is normally
            # empty to begin with, but a local or repeated run against an existing checkout can
            # find a CA too old to sign with. Reusing it silently would produce certificates that
            # fail every handshake for no visible reason.
            logger.info(
                f"Replacing the CA in {self.output_dir}: it is valid "
                f"{ca.not_valid_before_utc:%Y-%m-%d} to {ca.not_valid_after_utc:%Y-%m-%d}, "
                f"which leaves less than {self.MIN_CA_VALIDITY} of validity"
            )
        return self.generate_ca()

    def load_ca(self) -> tuple[RSAPrivateKey, Certificate]:
        with open(self.path(self.CA_KEY_FILENAME), "rb") as f:
            root_ca_key = serialization.load_pem_private_key(f.read(), password=None)
        with open(self.path(self.CA_CERT_FILENAME), "rb") as f:
            root_ca_cert = load_pem_x509_certificate(f.read())
        return root_ca_key, root_ca_cert

    def _check_if_ca_exists(self) -> bool:
        return all(
            os.path.exists(self.path(name))
            for name in (self.CA_CERT_FILENAME, self.CA_KEY_FILENAME)
        )

    def _ca_is_usable(self, ca: Certificate) -> bool:
        """Whether `ca` is currently valid and has `MIN_CA_VALIDITY` left to sign with.

        Deliberately not "outlives the certificates it signs": a CA is reused across calls, so
        it is always slightly older than what it signs, and requiring full coverage would mean
        never reusing one.
        """
        return (
            ca.not_valid_before_utc <= self.not_valid_before
            and ca.not_valid_after_utc >= self.not_valid_before + self.MIN_CA_VALIDITY
        )

    def _get_subject(self, common_name: str) -> Name:
        return Name([
            NameAttribute(NameOID.COUNTRY_NAME, 'US'),
            NameAttribute(NameOID.ORGANIZATION_NAME, 'Couchbase'),
            NameAttribute(NameOID.ORGANIZATIONAL_UNIT_NAME, 'Perf Team'),
            NameAttribute(NameOID.COMMON_NAME, common_name),
        ])

    def _make_key_pair(self) -> RSAPrivateKey:
        """Generate an RSA public/private key pair."""
        return generate_private_key(
            public_exponent=65537,
            key_size=2048,
        )

    def _store_file(self, filepath: str, file_bytes: bytes, mode: int = 0o644) -> str:
        os.makedirs(os.path.dirname(filepath) or ".", exist_ok=True)
        with os.fdopen(
            os.open(filepath, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, mode), "wb"
        ) as file:
            os.fchmod(file.fileno(), mode)
            file.write(file_bytes)
        return filepath

    def _store_key(self, filepath: str, key: RSAPrivateKey) -> str:
        return self._store_file(
            filepath,
            key.private_bytes(
                encoding=serialization.Encoding.PEM,
                format=serialization.PrivateFormat.TraditionalOpenSSL,
                encryption_algorithm=serialization.NoEncryption(),
            ),
            0o600,
        )

    def _store_cert(self, filepath: str, cert: Certificate) -> str:
        return self._store_file(filepath, cert.public_bytes(serialization.Encoding.PEM))

    def _store_pkcs12(
        self, key: RSAPrivateKey, cert: Certificate, ca: Certificate, storepass: str
    ) -> str:
        filepath = self.path(self.CLIENT_BUNDLE_FILENAME)
        # PBES1/3DES rather than the modern AES-256/PBES2 default: `keytool` has to read this
        # back on the workers, and older JREs cannot decrypt PBES2 bundles.
        encryption = (
            serialization.PrivateFormat.PKCS12.encryption_builder()
            .key_cert_algorithm(pkcs12.PBES.PBESv1SHA1And3KeyTripleDESCBC)
            .hmac_hash(hashes.SHA1())
            .build(storepass.encode())
        )
        return self._store_file(
            filepath,
            pkcs12.serialize_key_and_certificates(
                name=self.CLIENT_BUNDLE_ALIAS.encode(),
                key=key,
                cert=cert,
                cas=[ca],
                encryption_algorithm=encryption,
            ),
            0o600,
        )

    def _store_crl(self, filepath: str, crl: CertificateRevocationList) -> str:
        return self._store_file(filepath, crl.public_bytes(serialization.Encoding.PEM))

    def _next_crl_number(self) -> int:
        """Read previous CRL if one exists and return next valid CRL number.

        CRL numbers have to increase (RFC 5280 5.2.3) or a relying party holding an earlier CRL
        can't tell whether a new one supersedes it.
        """
        path = self.path(self.CRL_FILENAME)
        if not os.path.exists(path):
            return 1

        with open(path, "rb") as f:
            previous = load_pem_x509_crl(f.read())

        try:
            return previous.extensions.get_extension_for_class(CRLNumber).value.crl_number + 1
        except ExtensionNotFound:
            return 1

    def _get_general_name(self, host: str) -> GeneralName:
        # If the host address can pass as an IP v4 or v6 mark it as an IPAddress,
        # DNS name otherwise
        try:
            return IPAddress(ipaddress.ip_address(host))
        except Exception:
            return DNSName(host)
