---
# Create sync_gateway user
- hosts: syncgateways
  any_errors_fatal: true
  become: yes
  tasks:
  - include: tasks/create-sync-gateway-user.yml

# Download sync_gateway package
- hosts: syncgateways
  any_errors_fatal: true

  vars:
    couchbase_sync_gateway_package_base_url:
    couchbase_sync_gateway_package:
    couchbase_sync_gateway_package_url: "{{ couchbase_sync_gateway_package_base_url }}/{{ couchbase_sync_gateway_package }}"
    couchbase_server_primary_node: "{{ hostvars[groups.couchbase_servers[0]].ansible_host }}"

  tasks:
  - debug: msg="Downloading sync_gateway locally v. {{ couchbase_sync_gateway_package_url }}"
  - name: SYNC GATEWAY |  Download sync_gateway packages local
    get_url: url={{ couchbase_sync_gateway_package_url }} dest=/tmp/{{ couchbase_sync_gateway_package }}
    delegate_to: 127.0.0.1

  - debug: msg="Uploading SGW packages to remote servers. {{ couchbase_sync_gateway_package_url }}"
  - name: SYNC GATEWAY |  Copy sync_gateway packages to remote
    copy: src=/tmp/{{ couchbase_sync_gateway_package }} dest=/tmp/{{ couchbase_sync_gateway_package }}

# Deploy non writer sync_gateway configs
- hosts: syncgateways
  any_errors_fatal: true
  become: yes
  vars:
    sync_gateway_config_filepath:
    couchbase_server_primary_node: "{{ hostvars[groups.couchbase_servers[0]].ansible_host }}"
    # hack until mobile-testkit/issues/406 allows any sync gateway to be referenced
    sync_gateway_node: "{{ hostvars[groups.syncgateways[0]].ansible_host }}"
    is_index_writer: "false"
  tasks:
  - include: tasks/deploy-sync-gateway-config.yml

# Install and launch sync_gateway service
- hosts: syncgateways
  any_errors_fatal: true
  become: yes
  tasks:
  # Install and start service
  - name: SYNC GATEWAY | Install sync_gateway packages
    shell: dpkg -i /tmp/{{ couchbase_sync_gateway_package }}

  - name: SYNC GATEWAY | Start Sync gateway
    shell: systemctl start sync_gateway

  - name: SYNC GATEWAY | wait until sync gateway to listen on port
    wait_for: port=4985 timeout=600
