---
- hosts: syncgateways
  any_errors_fatal: true
  become: yes

  tasks:

  # Remove sync_gateway
  - include: tasks/remove-sync-gateway.yml

  # Remove nginx
  - include: tasks/remove-nginx.yml

  # # Delete sync_gateway uses
  - name: SYNC GATEWAY | Remove sync_gateway user
    user: name=sync_gateway state=absent remove=yes force=yes

  # Check no syncgateways or accels running
  - name: ALL | verify no sgs is running on 4985
    wait_for: port=4985 delay=1 state=stopped

  # Check no servers are running
  #- name: ALL | verify no servers not listening on port 8081
  #  wait_for: port=8091 delay=1 state=stopped
