---
- hosts: clients
  tasks:
  - name: upgrading packages on the system
    apt: upgrade=dist
  - name: installing additional packages
    apt:
     update_cache: yes
     name:
      - atop
      - cpufrequtils
      - git
      - golang-go
      - htop
      - libcurl4-gnutls-dev
      - libffi-dev
      - libsnappy-dev
      - libssl-dev
      - liblzma-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - libncursesw5-dev
      - linux-tools-generic
      - maven
      - nvi
      - openjdk-8-jdk
      - python3-pip
      - python3-virtualenv
      - python3-dev
      - sshpass
      - rpm2cpio
      - memcached
      - cmake
      - libicu-dev
  - name: disabling scheduled fstrim jobs
    file: path=/etc/cron.weekly/fstrim state=absent
