---
- hosts: all
  vars:
    unattended_upgrades_config: /var/lib/dpkg/info/unattended-upgrades.config
  tasks:
  - name: gather package facts
    package_facts:
      manager: auto

  - name: disable auto upgrades if unattended-upgrades is installed
    block:
    - name: configure unattended-upgrades to disable auto-updates
      debconf:
        name: unattended-upgrades
        question: unattended-upgrades/enable_auto_updates
        value: false
        vtype: boolean

    - name: rename unattended-upgrades config file so that it is ignored
      command: mv {{ unattended_upgrades_config }} {{ unattended_upgrades_config }}.ignore
      args:
        creates: "{{ unattended_upgrades_config }}.ignore"

    - name: apply unattended-upgrades configuration
      shell: dpkg-reconfigure -f noninteractive unattended-upgrades

    - name: restore unattended-upgrades config file to original name
      command: mv {{ unattended_upgrades_config }}.ignore {{ unattended_upgrades_config }}
      args:
        creates: "{{ unattended_upgrades_config }}"

    - name: print auto-upgrade status
      shell: apt-config dump APT::Periodic::Unattended-Upgrade
      register: auto_upgrade_status

    - debug:
        var: auto_upgrade_status.stdout_lines
    when: "'unattended-upgrades' in ansible_facts.packages"