---
- hosts: couchbase_servers
  vars:
    data_dir: /data
    disk: /dev/nvme2n1
  tasks:
    - name: re-creating filesystem
      filesystem:
        fstype: "xfs"
        dev: "{{ disk }}"
        force: yes

    - name: mounting data parition
      mount:
        name: "{{ data_dir }}"
        state: mounted
        src: "{{ disk }}"
        fstype: "xfs"

    - name: creating new "couchbase" group
      group: name=couchbase

    - name: creating new "couchbase" user
      user: name=couchbase group=couchbase

    - name: ensuring ownership of "{{ data_dir }}" directory
      file: path={{ data_dir }} owner=couchbase group=couchbase
