---
- hosts: kv:index:n1ql:analytics:eventing
  tasks:
  - name: creating a temporary directory
    tempfile:
      state: directory
    register: temp

  - name: downloading the specifed package
    get_url: url={{ url }} dest={{ temp.path }}
    register: package

  - name: installing the specifed package
    yum: name={{ package.dest }} state=present

  - name: removing temporary files
    file: path={{ temp.path }} state=absent

  - name: set vm.swappiness to 0
    shell: "echo 0 > /proc/sys/vm/swappiness"

  - name: disable thp
    shell: "echo never > /sys/kernel/mm/transparent_hugepage/enabled"
