---
# Copy of servers.yml, except we upgrade all packages first, due to the default
#  vagrant packages being outdated and then add the EPEL repo.
- hosts: kv:index:n1ql:analytics
  tasks:
  - name: Update all packages
    yum:
      name: '*'
      state: latest
  - name: Add EPEL Repository
    yum_repository:
      name: epel
      description: Yum EPEL repo
      baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
      gpgcheck: no
  - name: installing additional packages
    yum:
     state: latest
     name:
      - atop
      - fio
      - gdb
      - hdparm
      - htop
      - iotop
      - iperf
      - kernel-devel
      - kernel-headers
      - java-1.8.0-openjdk
      - lsof
      - moreutils
      - net-tools
      - numactl
      - psmisc
      - rsync
      - sysstat
      - tree
      - vim
      - wget
