---
- hosts: kv:index:n1ql:analytics
  vars:
    data_dir: /data
    opts: ""
    to_trim: 1
  tasks:
  - name: get the device name for the data dir
    shell: "df -P {{ data_dir }} | awk 'END{ print $1 }'"
    register: get_data_dir_device

  - set_fact:
      data_dir_device: "{{ get_data_dir_device.stdout }}"

  - name: umounting data parition
    mount:
      name: "{{ data_dir }}"
      state: unmounted
      src: "{{ data_dir_device }}"
      fstype: "{{ fstype | default('ext4') }}"

  - name: re-creating filesystem
    filesystem:
      fstype: "{{ fstype | default('ext4') }}"
      dev: "{{ data_dir_device }}"
      opts: "{{ opts }}"
      force: yes

  - name: get the uuid of the data device
    shell: "blkid -s UUID -o value {{ data_dir_device }}"
    register: get_data_dir_device_uuid

  - set_fact:
      data_dir_device_uuid: "{{ get_data_dir_device_uuid.stdout }}"

  - name: mounting data parition
    mount:
      name: "{{ data_dir }}"
      state: mounted
      src: "UUID={{ data_dir_device_uuid }}"
      fstype: "{{ fstype | default('ext4') }}"

  - name: discarding unused blocks
    shell: fstrim -v {{ data_dir }}
    when: to_trim == 1
