apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    config.couchbase.com/version: 2.3.0
  creationTimestamp: null
  name: couchbase-operator-admission
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    config.couchbase.com/version: 2.3.0
  creationTimestamp: null
  name: couchbase-operator-admission
rules:
- apiGroups:
  - couchbase.com
  resources:
  - couchbaseclusters
  - couchbasebuckets
  - couchbaseephemeralbuckets
  - couchbasememcachedbuckets
  - couchbasereplications
  - couchbaseusers
  - couchbasegroups
  - couchbaserolebindings
  - couchbasebackups
  - couchbasebackuprestores
  - couchbaseautoscalers
  - couchbasecollections
  - couchbasecollectiongroups
  - couchbasescopes
  - couchbasescopegroups
  - couchbasemigrationreplications
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    config.couchbase.com/version: 2.3.0
  creationTimestamp: null
  name: couchbase-operator-admission
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: couchbase-operator-admission
subjects:
- kind: ServiceAccount
  name: couchbase-operator-admission
  namespace: default
---
apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURoekNDQW0rZ0F3SUJBZ0lRZGdGSzJOMDRHYXhxbzBKcDBjSDdkVEFOQmdrcWhraUc5dzBCQVFzRkFEQXEKTVNnd0pnWURWUVFERXg5amIzVmphR0poYzJVdGIzQmxjbUYwYjNJdFlXUnRhWE56YVc5dUlFTkJNQjRYRFRJeQpNREl5T0RFM01qSTBOMW9YRFRNeU1ESXlOakUzTWpJME4xb3dKekVsTUNNR0ExVUVBeE1jWTI5MVkyaGlZWE5sCkxXOXdaWEpoZEc5eUxXRmtiV2x6YzJsdmJqQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0MKZ2dFQkFPYlNLamd1MDZQMVA3ZTRWdHM5ZVFYWi9rTXdhdlp1RXVzMW41ekJiMnBZaFRnLys5b3VKK2FtUzlyVQpVWWJrM0VzakZVZkJzL0J1NlIvSnpDcVFqL2M4ZENveTNUclZzTlhDVGYyU282QVZ1SDhXajdlNGMvUHdKenVFCm1BcmNjUG4xb0FHWDQ4TSs2RlRhNjBZaWRvckxvcVJ6WkNLbWFTNHBRczNjczRHajVKMmg2L0xCWWp3dUNXQzAKenpiVzh5aWNSL1pmbXA5ek1mYWM2ajNqblB0eXc5NUx2eGd1cm9XWDI5OUwvWEF4SWh6S2VhdUFNNVAvL0h5UQorMTJCOEJmcnVoc0FGU1hrNlNaaTMxSHRGVDh2UEgvMHNKTzNyRWtteDRHQWV1b2t5TmVZMG5IS0g4RVhkMUhlCjRhMkxqTllFeWxZZE5OTTZPZmdQRm4xZUdDRUNBd0VBQWFPQnF6Q0JxREFPQmdOVkhROEJBZjhFQkFNQ0JhQXcKRXdZRFZSMGxCQXd3Q2dZSUt3WUJCUVVIQXdFd0RBWURWUjBUQVFIL0JBSXdBREFkQmdOVkhRNEVGZ1FVY1JvWApUZ1UwcGJZbHl2dEpFVSs0UktrRVVSUXdId1lEVlIwakJCZ3dGb0FVZkM0aVZLeWhDT0dTWjQyUEg5LzBueDVJCkp0d3dNd1lEVlIwUkJDd3dLb0lvWTI5MVkyaGlZWE5sTFc5d1pYSmhkRzl5TFdGa2JXbHpjMmx2Ymk1a1pXWmgKZFd4MExuTjJZekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBaTVjS1lhUlBBL0UveEtMUk9SWXh5azhLa2Q1dAoyTU9kaittMVRCR2pTRWN2NDBmenNlNlJpUEMwbklVcnF5ajdBdEFNOFJla3BMb2tWakVuQkQyQ3ltdmFsR1F0ClExMi94bW81N25QVGV0dzhmWTdraHJrMUt2NnFkSXdickR6MUZiNFJKcS9uUDVmQVdZT09jZkVsYlUxM0VBakkKdzhZUFcwWFcxaTFOaGZYVElyWnY0VXdWYXJwUzdhQkhpbE9oZGp0YTFVNkEyMWI4dzZiY25PNitRbU9EakZBMQo0OGtLZG1NSU43ZnphVkRaZmhOM2Y4SjRhanp3QlVyRzc3SDhFR2d2UTk5VmJDWDhndWNReFdXNlJWNTFXQ040Cms4VXE2NElBZFkyQlhudkdWcEI0QS9GVlgvd1NyU0ZoNDRGQkl4SFNjVWw3SXdqeUdkc0xmbVRYRnc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBNXRJcU9DN1RvL1UvdDdoVzJ6MTVCZG4rUXpCcTltNFM2eldmbk1GdmFsaUZPRC83CjJpNG41cVpMMnRSUmh1VGNTeU1WUjhHejhHN3BIOG5NS3BDUDl6eDBLakxkT3RXdzFjSk4vWktqb0JXNGZ4YVAKdDdoejgvQW5PNFNZQ3R4dytmV2dBWmZqd3o3b1ZOcnJSaUoyaXN1aXBITmtJcVpwTGlsQ3pkeXpnYVBrbmFIcgo4c0ZpUEM0SllMVFBOdGJ6S0p4SDlsK2FuM014OXB6cVBlT2MrM0xEM2t1L0dDNnVoWmZiMzB2OWNERWlITXA1CnE0QXprLy84ZkpEN1hZSHdGK3U2R3dBVkplVHBKbUxmVWUwVlB5ODhmL1N3azdlc1NTYkhnWUI2NmlUSTE1alMKY2NvZndSZDNVZDdocll1TTFnVEtWaDAwMHpvNStBOFdmVjRZSVFJREFRQUJBb0lCQUZsUWMxUEFFdGE3bkVjcgp4amdaWmszMFZ5V0tnNmtOV0xhNHppVXEyRURQTmVWWkpNdjgxaVd5cldGa2pKTmsxVFVod3ljNzliT1FSeGFzCjBCcWNTNGpBVkxiTGJiMUpXSjZ1QzkyVnMwakxmdE4yV0hBZnFJWjRvOFdzL2VRZC9uMUtKUHJZMmlIL29vakwKR1FUUGF3MHoxS0JMb2pDaU1jclIzbTZuK3JHcmpDbUt0YThURkFMVW5TOTFPR0U5YzR0UjM4QjMzdGtPbGRyQQpBcWd3RnRxMFk3cXovL2RTWmdtRXloL1V2aDI1cTA2L0dhalJGMmVaT0NDWFo0VzM2MWtPUWNkbjZ1djhnZ1NDClRoZ1BxZXBKSGJ4NEZ0V2FJZytiaHIrYjUwaHVuZHlKbTB3MnRpaGlHUS9CdmxDMDNCVlgwUWRHbmd2SFpabysKNnV0ZDhTMENnWUVBK1Ryd2txQ01TeXE4UkUrY2U1Um16ZUx1aEJyUWdvb1JUSWl0ZEZPV3pIV2hXOGRmNm9QWgpHVXd6bEJ0endGRXh2NWNpOUg2VTVnL2wrMnJkOEh2Sy9WeEdwSjZIRzVoS1RsQXZXODkyeXExN2R4RC84TXVLCnBTRDNYbzV6SlhVbkdneGpmWkMrNjFmVllxbk4rNzFsY3g3OVd4UkVEMmNwWHVjTndhR0E5WXNDZ1lFQTdSYzIKcHMxOWgvMzhKd0lSeS80MElmNWMrOThkd1FFbHgvcVVycE9nYTlPckh6RTk0RWE5Zk11SGVhaVVUMDYvME9yTgpjWE5hejNFM3Nrb1Z1djBFYXJQZ0svM1FMcm1EVTEwYnB5Nkl6a29vak9VemNrUHBPNnlKQjdQY1ZXY3p2N09QCm40czBvWW1jTWMvNzF0ZHFDc3JkNWw0Ym1UcDI1eEFja1BPamxvTUNnWUVBMDNXN3Fsekh5L3I5YytRc08vb2sKNDZrWWdFT1VDRDRIQVcyeDVkSUtUMzI2bzNsZEcwZzFDaTdLVUc2ZVhsMUZuVzRwZlZKdEdXb0IwcmpRaC9zdwp0cGoxWXpVU0kwcXFPUm4xcEtzNCtpd0pabk9wQkhCZU9VN29NM1VmbzNkcjdzRDJKUktMdW5oeWwxekZaVU5ECjhWSW8ybjh1WS9jK2RjUUt1dkJCejVNQ2dZRUF1anJmck1vQWJvK3NQcCs3aHZhWDBKUFNTZTJKbTQ3aE5HRzUKNUI4RmhXendIMEk0ampCQ3F3SGIyazMyb1EwRVVuLzgrNzVXZUZkQUhvVmU2RS9SNWxhQUlVM3U5cVMxYVFmYgpyc2c0b1lGU3RNbGNUY2JXTHc5cFcybUdDbmRVQ0tKc2tDOXlHZWpUamJVRzVreXllT084eFRUcWpNT0ZuaDNqCnNtQU9BUzBDZ1lBYzI3QWtia3NsemxCaVQ3dU5OQmpDNWFkc3kySmpocHVJWTRHczJQRzcyTEZUSHErc0wvUksKWDcvSnZRbFZBREdwRFB1czZRUWVnbWUwMmhockptdTZYZ091T2kra1paUTRNcnp3R1gvVlRPQXhDbnVvaHFnNAphQUFQejRteGRkSW1RemU1YUxiNWVBakdkdDg2Y01NbVhScEJhZSsxdjZhWmo0ZXV4TmtOenc9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
kind: Secret
metadata:
  annotations:
    config.couchbase.com/version: 2.3.0
  creationTimestamp: null
  name: couchbase-operator-admission
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    config.couchbase.com/version: 2.3.0
  creationTimestamp: null
  name: couchbase-operator-admission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchbase-operator-admission
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: couchbase-operator-admission
    spec:
      containers:
      - args:
        - -zap-log-level=info
        - -tls-cert-file=/var/run/secrets/couchbase.com/couchbase-operator-admission/tls.crt
        - -tls-private-key-file=/var/run/secrets/couchbase.com/couchbase-operator-admission/tls.key
        - -validate-secrets=true
        - -validate-storage-classes=true
        - -default-file-system-group=true
        command:
        - couchbase-admission-controller
        image: couchbase/admission-controller:build
        imagePullPolicy: IfNotPresent
        name: couchbase-operator-admission
        ports:
        - containerPort: 8443
          name: https
        readinessProbe:
          httpGet:
            path: /readyz
            port: https
            scheme: HTTPS
        resources: {}
        volumeMounts:
        - mountPath: /var/run/secrets/couchbase.com/couchbase-operator-admission
          name: couchbase-operator-admission
          readOnly: true
      securityContext:
        runAsNonRoot: true
      serviceAccountName: couchbase-operator-admission
      volumes:
      - name: couchbase-operator-admission
        secret:
          secretName: couchbase-operator-admission
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    config.couchbase.com/version: 2.3.0
  creationTimestamp: null
  name: couchbase-operator-admission
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: couchbase-operator-admission
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    config.couchbase.com/version: 2.3.0
  creationTimestamp: null
  name: couchbase-operator-admission
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJRENDQWdpZ0F3SUJBZ0lRVDhYNDNQUHdVMVYwNzREMW5LeGhnREFOQmdrcWhraUc5dzBCQVFzRkFEQXEKTVNnd0pnWURWUVFERXg5amIzVmphR0poYzJVdGIzQmxjbUYwYjNJdFlXUnRhWE56YVc5dUlFTkJNQjRYRFRJeQpNREl5T0RFM01qSTBOMW9YRFRNeU1ESXlOakUzTWpJME4xb3dLakVvTUNZR0ExVUVBeE1mWTI5MVkyaGlZWE5sCkxXOXdaWEpoZEc5eUxXRmtiV2x6YzJsdmJpQkRRVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0MKQVFvQ2dnRUJBTEJva2xZZkE3UjlTN2xjZDI3MUFlK1E5anNZRm1IZ2w2TCtVN3JINDNzaXpSZ0Zid0cxMU5RZQpSeEQwUmhadnZZRGVEaHhRaEZQY3VpL2RpeFpTQXA5OGhucE8zandzNzh0RG1TTnVQeHlwTDBXZWMrMkJDR2RPCkYwSWpubTN4Zm45SWdnQnRmRHJvUWZYYStmd1FTY1BuOVZKR0NjaHlqQUg2RVBvN3hlQkN6eWdoeTR2M1ZTaHMKYVpWdGlXdVZoNEpVNVU5QmFFY3RJQ2d1ejFVSWViNFNJajRaQ1h5WCtWMzJiZkphMjRUZGJuUXpyemlUOHFHbApNVm4zVEh5MWtkZHFDNm9xWmZFcStZU01Tc3dzZGpJNFJ4M2pLVGNXdkhYbUNYN0dIU0xVNk81K0FHa1hBbWVMCjJBdnhKeXFwd2s1d1hweEdKc0tTUDQ3T2NPMFRTUWtDQXdFQUFhTkNNRUF3RGdZRFZSMFBBUUgvQkFRREFnRUcKTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkh3dUlsU3NvUWpoa21lTmp4L2Y5SjhlU0NiYwpNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUFPUC8wRlZpQmRCYS9RK0lScmZwYlg0czkzbzVFRWpIem8rTEE0CndjMk8zVm5KUzZ3UGY3SmdiUTJQMnlKWlZtcnAyRXhNaFpOZjhPcyt2VzVKdG91Mk5qUTdWVUJ2b0l1MG5HUFEKWm1LY0YyT1NMRjgrb1ViWXhlSkd2NUpEUFEzblRoZHlMRGRqMFZkZ0tiSTZYL2d2anRrVzBoS2EreGI1YmFYawpiUC9lLzJlY0JYSTFHc0hSQjFKVGtHKzNrS3R0Zk1ZUXBhUG00d2Q5aWloVWkwMnA1b0ZtRHQxdWJCZ2VFOTRkCnVaK2E0V1dTM1ZpYTlYdDhKMUNrMXhnYnBOYU82ZTQvTi9wT1VCNGFGSGlDQ2VHR0FwblY3U3VIaHhVTDcxL2MKS2FxY24zZS9jSW51MDA3bUVvMDF5MEVyZnlKK1JNWkJRQTZoL09Wb25ZZnpkZDU2Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: couchbase-operator-admission
      namespace: default
      path: /couchbaseclusters/validate
  failurePolicy: Fail
  name: couchbase-operator-admission.default.svc
  rules:
  - apiGroups:
    - couchbase.com
    apiVersions:
    - v1
    - v2
    operations:
    - CREATE
    - UPDATE
    resources:
    - couchbaseclusters
    - couchbasebuckets
    - couchbaseephemeralbuckets
    - couchbasememcachedbuckets
    - couchbasereplications
    - couchbaseusers
    - couchbasegroups
    - couchbaserolebindings
    - couchbasebackups
    - couchbasebackuprestores
    - couchbaseautoscalers
    - couchbasecollections
    - couchbasecollectiongroups
    - couchbasescopes
    - couchbasescopegroups
    - couchbasemigrationreplications
  sideEffects: None
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    config.couchbase.com/version: 2.3.0
  creationTimestamp: null
  name: couchbase-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    config.couchbase.com/version: 2.3.0
  creationTimestamp: null
  name: couchbase-operator
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - couchbase.com
  resources:
  - couchbaseclusters
  - couchbaseclusters/finalizers
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - couchbase.com
  resources:
  - couchbasereplications
  - couchbasemigrationreplications
  - couchbaseusers
  - couchbasegroups
  - couchbaserolebindings
  - couchbasebackups
  verbs:
  - list
  - watch
- apiGroups:
  - couchbase.com
  resources:
  - couchbasebuckets
  - couchbaseephemeralbuckets
  - couchbasememcachedbuckets
  - couchbasescopes
  - couchbasescopegroups
  - couchbasecollections
  - couchbasecollectiongroups
  verbs:
  - list
  - watch
  - create
- apiGroups:
  - couchbase.com
  resources:
  - couchbasebackuprestores
  verbs:
  - list
  - watch
  - delete
- apiGroups:
  - couchbase.com
  resources:
  - couchbaseautoscalers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - couchbase.com
  resources:
  - couchbaseautoscalers/status
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - create
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  - pods/status
  - services
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - list
  - create
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - create
  - update
  - list
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - get
  - create
  - delete
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - create
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    config.couchbase.com/version: 2.3.0
  creationTimestamp: null
  name: couchbase-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: couchbase-operator
subjects:
- kind: ServiceAccount
  name: couchbase-operator
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    config.couchbase.com/version: 2.3.0
  creationTimestamp: null
  name: couchbase-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchbase-operator
  strategy: {}
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8383"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: couchbase-operator
    spec:
      containers:
      - args:
        - --pod-create-timeout=10m0s
        - --zap-log-level=info
        command:
        - couchbase-operator
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: couchbase/operator:build
        imagePullPolicy: IfNotPresent
        name: couchbase-operator
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8383
          name: prometheus
        readinessProbe:
          httpGet:
            path: /readyz
            port: http
            scheme: HTTP
        resources: {}
      securityContext:
        runAsNonRoot: true
      serviceAccountName: couchbase-operator
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    config.couchbase.com/version: 2.3.0
  creationTimestamp: null
  name: couchbase-operator
spec:
  ports:
  - name: http-pprof
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: http-prometheus
    port: 8383
    protocol: TCP
    targetPort: 8383
  selector:
    app: couchbase-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    config.couchbase.com/version: 2.3.0
  creationTimestamp: null
  name: couchbase-backup
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    config.couchbase.com/version: 2.3.0
  creationTimestamp: null
  name: couchbase-backup
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - couchbase.com
  resources:
  - couchbasebackups
  - couchbasebackuprestores
  verbs:
  - get
  - list
  - watch
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    config.couchbase.com/version: 2.3.0
  creationTimestamp: null
  name: couchbase-backup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: couchbase-backup
subjects:
- kind: ServiceAccount
  name: couchbase-backup
  namespace: default