apiVersion: couchbase.com/v2
kind: CouchbaseCluster
metadata:
  name: cb-example-perf
spec:
  image: couchbase/server:build
  antiAffinity: true
  networking:
    networkPlatform: Istio
  security:
    adminSecret: cb-example-auth
    rbac:
      managed: true
      selector:
        matchLabels:
          cluster: cb-example-perf
  monitoring:
    prometheus:
      enabled: true
      image: couchbase/exporter:build
      refreshRate: XX
  buckets:
    managed: true
  backup:
    managed: true
    image: couchbase/operator-backup:build
    imagePullSecrets:
      - name: regcred
    serviceAccountName: couchbase-backup
    nodeSelector:
      NodeRoles: backups1
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  cluster:
    dataServiceMemoryQuota: 256Mi
    indexServiceMemoryQuota: 256Mi
    indexStorageSetting: memory_optimized
    autoFailoverTimeout: 120s
    autoFailoverMaxCount: 3
    autoFailoverOnDataDiskIssues: true
    autoFailoverOnDataDiskIssuesTimePeriod: 120s
    autoFailoverServerGroup: false
    autoCompaction:
        databaseFragmentationThreshold:
          percent: 100
        parallelCompaction: true
        timeWindow:
          abortCompactionOutsideWindow: false
          start: "00:01"
          end: "23:59"
        tombstonePurgeInterval: 72h0m0s
        viewFragmentationThreshold:
          percent: 30
  servers:
  - size: node_count
    name: data
    services:
    - data
    volumeMounts:
      default: couchbase_kv
    pod:
      metadata:
        annotations:
          sidecar.istio.io/inject: "true"
      spec:
        nodeSelector:
          NodeRoles: couchbase1
          kv_enabled: "true"
        imagePullSecrets:
          - name: regcred
  volumeClaimTemplates:
  - metadata:
      name: couchbase_kv
    spec:
      storageClassName: perf-sc
      resources:
        requests:
          storage: 1000Gi
  networking:
    exposeAdminConsole: true
    exposedFeatures:
    - client