apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    config.couchbase.com/version: 2.6.0
  creationTimestamp: null
  name: couchbase-operator-admission
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    config.couchbase.com/version: 2.6.0
  creationTimestamp: null
  name: couchbase-operator-admission
rules:
- apiGroups:
  - couchbase.com
  resources:
  - couchbaseclusters
  - couchbasebuckets
  - couchbaseephemeralbuckets
  - couchbasememcachedbuckets
  - couchbasereplications
  - couchbaseusers
  - couchbasegroups
  - couchbaserolebindings
  - couchbasebackups
  - couchbasebackuprestores
  - couchbaseautoscalers
  - couchbasecollections
  - couchbasecollectiongroups
  - couchbasescopes
  - couchbasescopegroups
  - couchbasemigrationreplications
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    config.couchbase.com/version: 2.6.0
  creationTimestamp: null
  name: couchbase-operator-admission
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: couchbase-operator-admission
subjects:
- kind: ServiceAccount
  name: couchbase-operator-admission
  namespace: default
---
apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURoekNDQW0rZ0F3SUJBZ0lRUW5OT3lKQUJwK0ZFdzAwUlRmajQvakFOQmdrcWhraUc5dzBCQVFzRkFEQXEKTVNnd0pnWURWUVFERXg5amIzVmphR0poYzJVdGIzQmxjbUYwYjNJdFlXUnRhWE56YVc5dUlFTkJNQjRYRFRJeQpNVEV3TVRBM05USXpNVm9YRFRNeU1UQXlPVEEzTlRJek1Wb3dKekVsTUNNR0ExVUVBeE1jWTI5MVkyaGlZWE5sCkxXOXdaWEpoZEc5eUxXRmtiV2x6YzJsdmJqQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0MKZ2dFQkFLZWlpQVVHbUhBUTRrWkpPV3BHaWRkd2g1dEhub1NnZ0hTNVR4SmFYMlVJUjQ0dkN2R1QwYlVYT1htOQpsbDM5S1gyaVdEZGh2a0YzT3BVVGZLcnZzV01BN04yODBpdjc3b0NIMmtsQzkybGZvWWxFSHdEQTZyTStwYlZ5CjFWRFZvS29ETHVjVytTV0JIOUpUV1hDMFNzT1lkZGlDRGR4RUR5TG0wQlNGZXRSS1RDdmNTNVRWNCt6bEFtWWMKaURtNHpsNUFWMlRGUE81dFdnOXc3NnFyVUxmSURaTnNESDNNNkdHTTIxT2MrbTloUmRGUmhwWHFXOUtKTjlpMQpDTTF3YVFyc1dJaWhDTldDOGhGRVRQOUUzWmdIVE5kNGRyenJSMHVVUlZ2UXhjUTNTS25EMTNKbVFZbzFFN2ZSCnA1RWlORk1Ud2h3STM0Qy94YWFwVnZ5cm1YRUNBd0VBQWFPQnF6Q0JxREFPQmdOVkhROEJBZjhFQkFNQ0JhQXcKRXdZRFZSMGxCQXd3Q2dZSUt3WUJCUVVIQXdFd0RBWURWUjBUQVFIL0JBSXdBREFkQmdOVkhRNEVGZ1FVTERIVApoNGJ3QWhPQjExM082S1BXVlBzSVI5b3dId1lEVlIwakJCZ3dGb0FVM3ZVcFZZS0JuYWYrMHlJSnhEWmlnT0ZPCnRqMHdNd1lEVlIwUkJDd3dLb0lvWTI5MVkyaGlZWE5sTFc5d1pYSmhkRzl5TFdGa2JXbHpjMmx2Ymk1a1pXWmgKZFd4MExuTjJZekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBcmI1Z3ZVbklsUm9RQ0N2WU10QitWQVVhc29oegpwTFNic3lzZ2JmZUZiV0pqTTBQWjJxbStna3ZMSy9DUmpEdnB0SHRiZnlOQXcwTXFzc3hPR2dYbXE2dVVWVXdiClYvTE4zZW5mNi9JMTJvQ2dKd3ZqOXJiMGloUXRuTVRxaUVDS2MwMHFsN2x0K1JYRzVaUnBFUlJMRS9ncG9xcncKU1NEQUpDWUFWZ2REWXRNc0RuclRIY09VZ202SFJjV1NScUN1ZlBLem51K1JteGxjY2VvK0hJaW1sNTl2REV1ZQpuT1luSVZIRlFxVjFBUjNOOGhML1pNNVVTenArT1V5dDNhenpIQm1CTDM3QjVoRjhTMU05TFI1S0o5RjhrU0JTCnN0MlhJRnNpWlhZajJpV0pvLzRlUngrNnF0TDRRQVc5M2ZIaWhKaUJVTE9wTkpRMGpXMnFxM0thVVE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBcDZLSUJRYVljQkRpUmtrNWFrYUoxM0NIbTBlZWhLQ0FkTGxQRWxwZlpRaEhqaThLCjhaUFJ0UmM1ZWIyV1hmMHBmYUpZTjJHK1FYYzZsUk44cXUreFl3RHMzYnpTSy92dWdJZmFTVUwzYVYraGlVUWYKQU1EcXN6Nmx0WExWVU5XZ3FnTXU1eGI1SllFZjBsTlpjTFJLdzVoMTJJSU4zRVFQSXViUUZJVjYxRXBNSzl4TApsTlhqN09VQ1poeUlPYmpPWGtCWFpNVTg3bTFhRDNEdnFxdFF0OGdOazJ3TWZjem9ZWXpiVTV6NmIyRkYwVkdHCmxlcGIwb2szMkxVSXpYQnBDdXhZaUtFSTFZTHlFVVJNLzBUZG1BZE0xM2gydk90SFM1UkZXOURGeERkSXFjUFgKY21aQmlqVVR0OUdua1NJMFV4UENIQWpmZ0wvRnBxbFcvS3VaY1FJREFRQUJBb0lCQVFDa0RIdCtKNWt3T21XbAprTzBlSXMrc1JOU0FVbE0veVc1TVREaWtaa3BxcmZLUW8xcmJWT1JwaXNQVmJvSmprbWR6S2xlWVF4QVVNdURpCm1NSnM2Y3EzYjJWZURmWEQwM1R3MVlINkpnM0hVaTNjRGcwbENLWG1LYzJ5eHlFWVRTZEFtWUxoNVdxR21GbVMKMDd4NGZnZVlhSEFUSkJyNlRxUmRiSEYvVTYwRForaXF0TVU1TXlPalBnM2NuQnBPcE85M24rV3lCcEhKdnRtawpqTE1SaHBkQmRWRTBqc3RGaVdlZGljbmdGdzR4U1JQeitSSjVvT29XVzJSd1hHTjNjQVdicVdZbEJONVl0OFNPClZYZHZZYVVDd0J5TzRDTnpjK2V0ZVM4bVkvWCtVNkpCN0t6YXJaWkxnb2prMUlCRThUUllBbE1mRXJTV1NjRkIKenRjSFJVVXRBb0dCQU5IZS9BVzhXWTBjM2I4aWtYYnhLZ24wYWh3UkxWdzdJRGNVcjkxTS8vdUxmRWFHR3Y0ZAovWG0vYm44RURZVlBaQmkvU3VTREdPeTlyRXRpSWVDUWgrUzNnZC9yWjhReG5GRWZ3QkY0dUNpV1VVSUpwTE5iCkFnbll6cFJqbGJXcDdRV2lSc2pqcjFmR2NJTkp3SXhnM3p0Z2hiRUk0Ynh6MmNEUzRqN09QTGpyQW9HQkFNeDcKQVVpU2I1NWNNN0ZQSG5QMDBEaUJuUHk2RllKdERoQnF4TDdhYUZLcmpKNDlGWGgwQTFGdllrMjUzVXJPQzNQMgo5SFVvVHFXZEJwM1dpSG4xVHpFdnZUZW1Sc3hSMTI2QVhQWFZUSmpDdkVhY0l5Rm40SWlzRVdPZFVXc1B5aXR3CjFxc3hrOE50MzZwWGdrSldEMXN1OCs5dnFaVkhCOUE2VzJEYUJhQVRBb0dBSTRFVW82ZkVncEhpbGFZMGM2bkMKMGVKT1hTY3V4RTZnV1pFZlcxSGVjR0NkaXBTL1ZrUWVrSTBwRlVYTFA4VTVpdEk1eWtTL1g3V0t3MG43cnpEawpQSFlxKzRXb2pWRlRQNG9laFJZbUdYK3NpWDUySlgxODc4dUV6eWUxdVFEaFB6Vy93ZFo2NEYrS3d6c2ozdHU0CmlDUUJHZjBGcTByeUNLUGtjSG1WWGpjQ2dZRUFvc2ZaUWJpeGV0UFRvdmRsT3RKTllHNXVWeEtjUlBRa0doV2wKQW5wRVNtdWV5ZW0reWVFeE13Y0Vydk9qb3dWY1FMajc2cmhudzVlNXlMVWNlRm84N044Z05zajcyM1BibUhBLwprTVI0OGJNMHh0Rk5kaTZIcE1XMklpTCt5Y2dNSFlENm85WVgxNkFFU2tyWHU0OWZNaXV5clkycTV0ZGc5UGMvCi8xNFExRmtDZ1lFQWxhWm5hTVVEd2swTFI4MjRqekd2MUtubHJaeWhTZlpzMzNmN1B2QWpPNzg2UWZwVDdqMTMKMDVGTVFjaUliUE1CNDRsd1M1c2VYUlVqd0lJdG1HWWJMMG5KNVUyMnhnVVJWRjMrdHdLSWJyNnBMSzFSRm0vRwpRS01SdC9IckhOamVRRzludWJVbmlaVGVnd1NzVy9ZNnVxMXJaRFE0UlorL1FHWFJtVjJWNVU0PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
kind: Secret
metadata:
  annotations:
    config.couchbase.com/version: 2.6.0
  creationTimestamp: null
  name: couchbase-operator-admission
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    config.couchbase.com/version: 2.6.0
  creationTimestamp: null
  name: couchbase-operator-admission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchbase-operator-admission
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: couchbase-operator-admission
    spec:
      containers:
      - args:
        - -zap-log-level=info
        - -tls-cert-file=/var/run/secrets/couchbase.com/couchbase-operator-admission/tls.crt
        - -tls-private-key-file=/var/run/secrets/couchbase.com/couchbase-operator-admission/tls.key
        - -validate-secrets=true
        - -validate-storage-classes=true
        command:
        - couchbase-admission-controller
        image: couchbase/admission-controller:build
        imagePullPolicy: IfNotPresent
        name: couchbase-operator-admission
        ports:
        - containerPort: 8443
          name: https
        readinessProbe:
          httpGet:
            path: /readyz
            port: https
            scheme: HTTPS
        resources: {}
        volumeMounts:
        - mountPath: /var/run/secrets/couchbase.com/couchbase-operator-admission
          name: couchbase-operator-admission
          readOnly: true
      securityContext:
        runAsNonRoot: true
      serviceAccountName: couchbase-operator-admission
      volumes:
      - name: couchbase-operator-admission
        secret:
          secretName: couchbase-operator-admission
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    config.couchbase.com/version: 2.6.0
  creationTimestamp: null
  name: couchbase-operator-admission
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: couchbase-operator-admission
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    config.couchbase.com/version: 2.6.0
  creationTimestamp: null
  name: couchbase-operator-admission
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJRENDQWdpZ0F3SUJBZ0lRU29yTzc1Wms5ZVluWnpwdG43ZmxxVEFOQmdrcWhraUc5dzBCQVFzRkFEQXEKTVNnd0pnWURWUVFERXg5amIzVmphR0poYzJVdGIzQmxjbUYwYjNJdFlXUnRhWE56YVc5dUlFTkJNQjRYRFRJeQpNVEV3TVRBM05USXpNVm9YRFRNeU1UQXlPVEEzTlRJek1Wb3dLakVvTUNZR0ExVUVBeE1mWTI5MVkyaGlZWE5sCkxXOXdaWEpoZEc5eUxXRmtiV2x6YzJsdmJpQkRRVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0MKQVFvQ2dnRUJBTFJGYXZVMHBQV0xTK1dBUElwU2ExeFZ2c1UvYUhCK3BNdnZWOEFGdEp5Y25VQWZqVE80eG5wSgpVRnhhOThiR2V6K1JFUGZPOFhGdE5YTm9lWVM5UXlqU0w3TjFtOTJ3MFlFZ2pFTzBFdDdESFplMTlsVS9qQkNoClFBQjBwOEY1RVVzNUh5YUQrTk4yeWEyS1R4YkFsZGpEMFprWjdQdlVmVWw2MGJGM3V0UVVYQ3N2VkZZRGNvUFUKTU1XNkYwRnBqc0NnN2I1K0JrRkdhUmw1eWJhRzR3KzJsdERGMWFJcTBqRHlrSXZoTlhCQzJuNjJqWUJkVkF6OApwd3dOdEFhTmJENGJWOFZ0aUMrUTdzOWU4cUppenVEZi81UUNJcldKYWY2ZXZkK3JISUlzK2NpcVBIQXBEWXBOCkRPOHVRc09VUE10UCsrVi9RV09vYmF5a253NWE0S0VDQXdFQUFhTkNNRUF3RGdZRFZSMFBBUUgvQkFRREFnRUcKTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRk43MUtWV0NnWjJuL3RNaUNjUTJZb0RoVHJZOQpNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUFMZU95b0p6enZIRTRZbmhuNjc3WnJCVmh3UjNqS0JubE1ubEp5Ckx3Qy9keXVaZktZSkhCYnBBQkR0RFRnY0lZVjl5VmI0TVU5dDJ2SGp0QjBlQms1dHNxSlBTZGZPK1g1b0dQYlUKWm5EM3dRalFobVVCcDhKMkJrY0lnTll2NXptU0dEbndlR0N3Z2l5MDB2enVPdS9jTWFGOFE5MWd2dGFvdGZLVgpHVUJnS1FuMklUZEpIMEZhbjluQi9SbzRPYVFYSUFYK2NqeUV0NmYwWTZLSEF2NzluSUdEMW5ibFFBMmdIWmRGCkhHNTFPWlFNWHRvOWszSG1DSHZpdkl2bFBKRUlPMHE3OFJuQzhxK3ZKamF3ejg3NEE3b2xlcllOTmJtSjRLd0oKMDVPa3JNN0tLRnVUdG90b0ZCakRYaDdYd1JMcWc0YSthenF2UW5PZFBLNml2Wkd1Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: couchbase-operator-admission
      namespace: default
      path: /couchbaseclusters/validate
  failurePolicy: Fail
  name: couchbase-operator-admission.default.svc
  rules:
  - apiGroups:
    - couchbase.com
    apiVersions:
    - v1
    - v2
    operations:
    - CREATE
    - UPDATE
    resources:
    - couchbaseclusters
    - couchbasebuckets
    - couchbaseephemeralbuckets
    - couchbasememcachedbuckets
    - couchbasereplications
    - couchbaseusers
    - couchbasegroups
    - couchbaserolebindings
    - couchbasebackups
    - couchbasebackuprestores
    - couchbaseautoscalers
    - couchbasecollections
    - couchbasecollectiongroups
    - couchbasescopes
    - couchbasescopegroups
    - couchbasemigrationreplications
  sideEffects: None
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    config.couchbase.com/version: 2.6.0
  creationTimestamp: null
  name: couchbase-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    config.couchbase.com/version: 2.6.0
  creationTimestamp: null
  name: couchbase-operator
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - couchbase.com
  resources:
  - couchbaseclusters
  - couchbaseclusters/finalizers
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - couchbase.com
  resources:
  - couchbasereplications
  - couchbasemigrationreplications
  - couchbaseusers
  - couchbasegroups
  - couchbaserolebindings
  - couchbasebackups
  verbs:
  - list
  - watch
- apiGroups:
  - couchbase.com
  resources:
  - couchbasebuckets
  - couchbaseephemeralbuckets
  - couchbasememcachedbuckets
  - couchbasescopes
  - couchbasescopegroups
  - couchbasecollections
  - couchbasecollectiongroups
  verbs:
  - list
  - watch
  - create
- apiGroups:
  - couchbase.com
  resources:
  - couchbasebackuprestores
  verbs:
  - list
  - watch
  - delete
- apiGroups:
  - couchbase.com
  resources:
  - couchbaseautoscalers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - couchbase.com
  resources:
  - couchbaseautoscalers/status
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  - pods/status
  - services
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - list
  - create
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - create
  - update
  - list
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - get
  - create
  - delete
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - create
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    config.couchbase.com/version: 2.6.0
  creationTimestamp: null
  name: couchbase-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: couchbase-operator
subjects:
- kind: ServiceAccount
  name: couchbase-operator
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    config.couchbase.com/version: 2.6.0
  creationTimestamp: null
  name: couchbase-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchbase-operator
  strategy: {}
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8383"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: couchbase-operator
    spec:
      containers:
      - args:
        - --pod-create-timeout=10m0s
        - --zap-log-level=info
        command:
        - couchbase-operator
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: couchbase/operator:build
        imagePullPolicy: IfNotPresent
        name: couchbase-operator
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8383
          name: prometheus
        readinessProbe:
          httpGet:
            path: /readyz
            port: http
            scheme: HTTP
        resources: {}
      securityContext:
        runAsNonRoot: true
      serviceAccountName: couchbase-operator
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    config.couchbase.com/version: 2.6.0
  creationTimestamp: null
  name: couchbase-operator
spec:
  ports:
  - name: http-pprof
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: http-prometheus
    port: 8383
    protocol: TCP
    targetPort: 8383
  selector:
    app: couchbase-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    config.couchbase.com/version: 2.6.0
  creationTimestamp: null
  name: couchbase-backup
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    config.couchbase.com/version: 2.6.0
  creationTimestamp: null
  name: couchbase-backup
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - couchbase.com
  resources:
  - couchbasebackups
  - couchbasebackuprestores
  verbs:
  - get
  - list
  - watch
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    config.couchbase.com/version: 2.6.0
  creationTimestamp: null
  name: couchbase-backup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: couchbase-backup
subjects:
- kind: ServiceAccount
  name: couchbase-backup
  namespace: default